#include "BMSSerialPacket.h"

const char* bmsInfoStatusReadSlot[] = {
   "Total voltage[1]",
   "Total voltage[0]",
   "Total current[1]",
   "Total current[0]",
   "Residual capacity[1]",
   "Residual capacity[0]",
   "Nominal capacity[1]",
   "Nominal capacity[0]",
   "Cycle times[1]",
   "Cycle times[0]",
   "Date of manufacture[1]",
   "Date of manufacture[0]",
   "Balance state low[1]",
   "Balance state low[0]",
   "Balance state high[1]",
   "Balance state high[0]",
   "Protection state[1]",
   "Protection state[0]",
   "Software version",
   "RSOC",
   "FET state",
   "Battery serial number",
   "NTC count",
   "NTC 1 temp[1]",
   "NTC 1 temp[0]",
   "NTC 2 temp[1]",
   "NTC 2 temp[0]",
};